### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by szepeviktor** [RebelCode/cronarchy#3]
Could you make and tag releases?

**Comment by mecha** [comment]
I'm a bit reluctant to encourage using this in production right now. This project had to be temporarily put on hold and so it remained in "prototype" phase since then, without any tests.

That said, how about an alpha release? That would at least allow you to install it with Composer.

**Comment by szepeviktor** [comment]
> That said, how about an alpha release? That would at least allow you to install it with Composer.

Yes!

**Comment by mecha** [comment]
[Done](https://github.com/RebelCode/cronarchy/releases/tag/v0.1.alpha).

**Comment by szepeviktor** [comment]
Maybe we need a dash before "alpha".

https://getcomposer.org/doc/articles/versions.md#vcs-tags-and-branches

**Comment by mecha** [comment]
Whoops! Corrected.
